package model;

import org.hibernate.*;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.math.*;
import java.util.*;

@Entity
@Table(name = "city")
public class City {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public int id;
    @NotNull
    public String name;
    public static String dropSQL = "Drop table city If Exists Cascade";
    public static String createSQL = "Create table city (" +
            "  id Integer Generated By Default As Identity(Start With 1) primary key," +
            "  name Varchar(50) Not Null" +
            ");";

    public static HashMap<Integer, String> retrieveAll(Session session) {
        HashMap<Integer, String> rslt = new HashMap<Integer, String>();
        String sql = "Select id, name From city";
        List<City> cities = session.createNativeQuery(sql).addEntity(City.class).list();
        for (City city : cities) {
            rslt.put(city.id, city.name);
        }
        return rslt;
    }

    public static JTableResult retrievePage(Session session, JTableRequest jTableRequest) {
        String orderBy = "name";
        if (jTableRequest.jtSorting != null) orderBy = jTableRequest.jtSorting;
        String sql = "Select id, name From city Order By " + orderBy + " Offset " + jTableRequest.jtStartIndex + " Limit " + jTableRequest.jtPageSize;
        List<City> cities = session.createNativeQuery(sql).addEntity(City.class).list();

        JTableResult rslt = new JTableResult();
        rslt.Result = "OK";
        rslt.Records = cities;
        rslt.TotalRecordCount = ((BigInteger) session.createNativeQuery("Select count(*) From city").getSingleResult()).intValue();

        return rslt;
    }

    public static String getNameById(Session session, int id) {
        return (String) session.createNativeQuery("Select name From city Where id = " + id).getSingleResult();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
