package dbsetup;

public class DataRepo {
    public static String[] city_data = new String[]
            {
                    "Adana",
                    "Amsterdam",
                    "Ankara",
                    "Athens",
                    "Bandung",
                    "Bangalore",
                    "Bangkok",
                    "Barcelona",
                    "Beijing",
                    "Berlin",
                    "Buenos Aires",
                    "Cairo",
                    "Cape Town",
                    "Chicago",
                    "Córdoba",
                    "Curitiba",
                    "Delhi",
                    "Donetsk",
                    "Eindhoven",
                    "Florence",
                    "Frankfurt",
                    "Glasgow",
                    "Gothenburg",
                    "Guangzhou",
                    "Hai Phong",
                    "Hamburg",
                    "Hanoi",
                    "Houston",
                    "Hyderabad",
                    "Istanbul",
                    "Izmir",
                    "Jakarta",
                    "Kraków",
                    "Kunming",
                    "Kyiv",
                    "Lisbon",
                    "Liverpool",
                    "London",
                    "Los Angeles",
                    "Lyon",
                    "Madrid",
                    "Manchester",
                    "Melbourne",
                    "Mexico City",
                    "Milano",
                    "Montreal",
                    "Moscow",
                    "Mumbai",
                    "Munich",
                    "New York",
                    "Nice",
                    "Nonthaburi",
                    "Paris",
                    "Petersburg",
                    "Porto",
                    "Rio de Janeiro",
                    "Rome",
                    "Salvador",
                    "São Paulo",
                    "Semarang",
                    "Shanghai",
                    "Stockholm",
                    "Surabaya",
                    "Sydney",
                    "Tijuana",
                    "Torino",
                    "Toronto",
                    "Toulouse",
                    "Volos",
                    "Warsaw"
            };

    public static String[][] person_data = new String[][]
            {
                    new String[]{"Halil", "Kalkan", "M"},
                    new String[]{"Karen", "Asimov", "F"},
                    new String[]{"Neo", "Gates", "M"},
                    new String[]{"Trinity", "Lafore", "F"},
                    new String[]{"Morpheus", "Maalouf", "M"},
                    new String[]{"Suzanne", "Hayyam", "F"},
                    new String[]{"Georghe", "Richards", "M"},
                    new String[]{"Steeve", "Orwell", "M"},
                    new String[]{"Agatha", "Jobs", "F"},
                    new String[]{"Stephan", "Christie", "M"},
                    new String[]{"Andrew", "Hawking", "M"},
                    new String[]{"Nicole", "Brown", "F"},
                    new String[]{"Thomas", "Garder", "M"},
                    new String[]{"Oktay", "More", "M"},
                    new String[]{"Paulho", "Anar", "M"},
                    new String[]{"Carl", "Sagan", "M"},
                    new String[]{"Daniel", "Radcliffe", "F"},
                    new String[]{"Rupert", "Grint", "M"},
                    new String[]{"David", "Yates", "M"},
                    new String[]{"Hercules", "Poirot", "M"},
                    new String[]{"Christopher", "Paolini", "M"},
                    new String[]{"Walter", "Isaacson", "M"},
                    new String[]{"Arda", "Turan", "M"},
                    new String[]{"Jeniffer", "Anderson", "F"},
                    new String[]{"Stephenie", "Mayer", "F"},
                    new String[]{"Dan", "Brown", "M"},
                    new String[]{"Clara", "Clayton", "F"},
                    new String[]{"Emmett", "Brown", "M"},
                    new String[]{"Marty", "Mcfly", "M"},
                    new String[]{"Jane", "Fuller", "F"},
                    new String[]{"Douglas", "Hall", "M"},
                    new String[]{"Tom", "Jones", "M"},
                    new String[]{"Lora", "Adams", "F"},
                    new String[]{"Andy", "Garcia", "M"},
                    new String[]{"Amin", "Collins", "M"},
                    new String[]{"Elmander", "Sokrates", "M"},
                    new String[]{"Austin", "Cleeve", "F"},
                    new String[]{"Audrey", "Cole", "F"},
                    new String[]{"Bella", "Clark", "F"},
                    new String[]{"Burley", "Pugy", "M"},
                    new String[]{"Charles", "Quiney", "M"}};

    public static String[] course_data = new String[]
            {
                    "Mathematics",
                    "Physics",
                    "Chemistry",
                    "Introduction to Programming I",
                    "Introduction to Programming II",
                    "Microcomputers",
                    "Probability",
                    "Fuzzy logic",
                    "Neural network",
                    "Experts systems",
                    "History",
                    "Data structures",
                    "Differential Equations",
                    "Lineer Algebra",
                    "Object oriented programming",
                    "Computer graphics",
                    "Artificial Intelligence",
                    "Foreign Language",
                    "Operating Systems",
                    "Database",
                    "Data communication",
                    "Finite-state machines",
                    "Compiler design",
                    "Computer vision",
                    "Computer networks I",
                    "Computer networks II",
                    "Wireless communication",
                    "Digital signal processing",
                    "Optimization",
                    "Robotics",
                    "Data mining"
            };
}
